[preload  storage="./data/fgimage/chara/2/幽灵眯眼笑.png"  ]
[preload  storage="./data/fgimage/chara/2/幽灵悲伤.png"  ]
[preload  storage="./data/fgimage/chara/2/幽灵微笑.png"  ]
[preload  storage="./data/fgimage/chara/2/幽灵苦笑.png"  ]
[preload  storage="./data/bgimage/1.jpg"  ]
[return]